version: "3.7"

services:
  postgres:
    image: postgres:13
    container_name: otus_postgres
    environment:
      POSTGRES_DB: demoDB
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    ports:
      - "5430:5432"

