spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  thymeleaf:
    enabled: true

logging:
  level:
    org:
      springframework:
        web: trace
        jdbc: trace
